version: '2.1'
volumes:
    data:
    xserver:
services:
  xserver:
    image: nucleardreamer/xserver
    restart: always
    privileged: true
    volumes:
      - 'xserver:/tmp/.X11-unix'
  wsf-ferry-schedule:
    build: .
    restart: always
    network_mode: host
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - 'data:/data/'
      - 'xserver:/tmp/.X11-unix'
    shm_size: '2gb'
    labels:
      io.balena.features.supervisor-api: 1
      io.balena.features.balena-api: 1
    environment:
      DEPARTING_ID: 9
      ARRIVING_ID: 22
      WSF_API_KEY: 'f68dac82-1e43-4c02-8589-c875a5b9663a'
