version: '2.1'
volumes:
    data:
services:
  wsf-ferry-schedule:
    build: .
    restart: always
    network_mode: host
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - 'data:/data/'
    shm_size: '2gb'
    labels:
      io.balena.features.supervisor-api: 1
      io.balena.features.balena-api: 1
    environment:
      DEPARTING_ID: 9
      ARRIVING_ID: 22
