version: '2.1'
volumes:
    data:
services:
  wsf-ferry-schedule:
    build: .
    restart: always
    network_mode: host
    privileged: true
    ports:
      - 8080:8080
    volumes:
      - 'data:/data/'
    shm_size: '2gb'
